### ISSUE TITLE
Wrong reference counts AND duplicated references

### ISSUE THREAD

**Issue by ericraider33** [jasonyingling/easy-footnotes#9]
I'm using the theme ‘color newsmagazine’ and the easy footnote plugin. I've verified that the plug-in calls content twice. The theme cause the reference counts to be wrong AND to duplicate the list of references on the page. To reproduce the issue, please see the link:

https://test-wordpress.chroniccareiq.com/2021/09/23/hello-world/

My suggested fix is to introduce a short code so that authors can manually reset the plug-in.  It is a fix that wouldn't break backwards compatibility and would make the plug-in work better with other themes.

Example code for implementing a 'reset' shortcode:

`add_shortcode( 'efn_reset', array( $this, 'short_code_reset' ) );

/**
 * Manually reset foot notes and counter
 */
public function short_code_reset() {
	$this->footnoteCount = 0;
	$this->footnotes = array();
	return "";
}`

**Comment by ericraider33** [comment]
@jasonyingling Can you merge the pull request for the EFN_RESET method?  The most recent update clobbered my local changes and jacked up my website. I'm sure it will help others with weird themes like the one I'm using.

https://github.com/jasonyingling/easy-footnotes/pull/10

**Comment by jasonyingling** [comment]
Very delayed, but I did release 1.1.9 with your shortcode merged in as well as with a feature added by another user to hopefully negate the need for it anyway.
